apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-db
  namespace: tienda
spec:
  # ... (resto de tu configuración igual)
  template:
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          # ... (tus env y ports iguales)
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql # Aquí ocurre la magia
              subPath: init.sql
      volumes:
        - name: data
          emptyDir: {}
        - name: init-script
          configMap:
            name: mysql-init-script